# Generated by Django 3.1 on 2020-09-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarif',
            name='input_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
