# Generated by Django 3.1 on 2020-08-30 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0002_auto_20200826_0815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarif',
            options={'ordering': ['price']},
        ),
        migrations.AddField(
            model_name='tarif',
            name='price_w_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='service',
            name='social_network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='cp.socialnetwork'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='cp.service'),
        ),
    ]
