# Generated by Django 3.1 on 2020-09-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0002_tarif_input_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarif',
            name='is_textarea',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tarif',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
