# Generated by Django 3.1 on 2020-09-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0003_auto_20200914_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
