# Generated by Django 3.1 on 2020-09-14 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0004_order_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarif',
            name='text',
        ),
    ]
