# Generated by Django 3.1 on 2020-09-09 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0005_auto_20200909_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='user',
            new_name='order',
        ),
    ]
